"use client";

import React, { useState } from "react";
import { ChevronDown, HelpCircle, AlertCircle, CheckCircle2, ShieldAlert } from "lucide-react";

interface FaqItem {
  id: string;
  question: string;
  category: "Connection" | "Installation" | "System";
  answer: React.ReactNode;
}

export function TroubleshootingFaq() {
  const [openIds, setOpenIds] = useState<string[]>(["item-1"]);

  const toggleItem = (id: string) => {
    setOpenIds((prev) =>
      prev.includes(id) ? prev.filter((item) => item !== id) : [...prev, id]
    );
  };

  const faqs: FaqItem[] = [
    {
      id: "item-1",
      question: "Extension Not Installed / Status shows 'Waiting'",
      category: "Connection",
      answer: (
        <div className="space-y-2.5 text-xs sm:text-sm text-slate-600 leading-relaxed">
          <p className="font-semibold text-slate-900">Possible causes:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>The browser extension has not been loaded yet in Chrome or Edge.</li>
            <li>The wrong browser extension ZIP was downloaded (e.g. Chrome ZIP on Edge or vice versa).</li>
            <li>The extension is toggled off in <code className="font-mono text-purple-700">chrome://extensions</code> or <code className="font-mono text-indigo-700">edge://extensions</code>.</li>
          </ul>
          <p className="font-semibold text-slate-900 mt-2">Recommended resolution:</p>
          <p>
            Open your browser extensions manager, ensure the FocusPet toggle is switched <strong>ON</strong>, and verify that the extension ID is registered in FocusPet Settings.
          </p>
        </div>
      ),
    },
    {
      id: "item-2",
      question: "Native host not connected",
      category: "Connection",
      answer: (
        <div className="space-y-2.5 text-xs sm:text-sm text-slate-600 leading-relaxed">
          <p className="font-semibold text-slate-900">Check the following items in order:</p>
          <ol className="list-decimal pl-5 space-y-1.5">
            <li><strong>FocusPet Desktop App is Running:</strong> Make sure the desktop companion is active on your screen or in your taskbar.</li>
            <li><strong>Extension is Enabled:</strong> Check <code className="font-mono">chrome://extensions</code> or <code className="font-mono">edge://extensions</code>.</li>
            <li><strong>Extension ID Registered:</strong> Copy the Extension ID shown by your browser and register it in <em>FocusPet &rarr; Settings &rarr; Developer &amp; Unpacked Extension Management</em>.</li>
            <li><strong>Restart:</strong> If you registered a new ID while the browser was open, restart your browser and FocusPet to initialize the native messaging channel.</li>
          </ol>
        </div>
      ),
    },
    {
      id: "item-3",
      question: "Load unpacked doesn't work / Browser gives folder error",
      category: "Installation",
      answer: (
        <div className="space-y-2.5 text-xs sm:text-sm text-slate-600 leading-relaxed">
          <p className="font-semibold text-slate-900">Ensure the following folder rules:</p>
          <ul className="list-disc pl-5 space-y-1.5">
            <li><strong className="text-amber-800">Did you extract the ZIP?</strong> You cannot select the <code className="font-mono">.zip</code> archive directly in the file picker. You must right-click &rarr; <em>Extract All...</em> first.</li>
            <li><strong className="text-slate-900">Select the folder containing manifest.json:</strong> When browsing folders in &quot;Load unpacked&quot;, click inside the extracted folder so that <code className="font-mono text-purple-700">manifest.json</code> is located directly in that directory.</li>
            <li><strong>Do NOT select <code className="font-mono">host_manifests</code>:</strong> The browser extension folder is <code className="font-mono">FocusPet-Chrome-Extension</code> or <code className="font-mono">FocusPet-Edge-Extension</code>.</li>
          </ul>
        </div>
      ),
    },
    {
      id: "item-4",
      question: "Extension ID changed after reloading",
      category: "Installation",
      answer: (
        <div className="space-y-2.5 text-xs sm:text-sm text-slate-600 leading-relaxed">
          <p>
            Unpacked development extensions can have a development ID generated by your local browser instance that differs from the production Chrome Web Store ID.
          </p>
          <p>
            If you moved the extracted folder to a new path or reloaded unpacked files with a new ID, simply copy the newly displayed Extension ID from <code className="font-mono">chrome://extensions</code> or <code className="font-mono">edge://extensions</code>, and paste it again in:
          </p>
          <div className="p-3 rounded-xl bg-purple-50 border border-purple-200 text-purple-900 font-mono text-xs font-semibold">
            FocusPet &rarr; Settings &rarr; Developer &amp; Unpacked Extension Management
          </div>
        </div>
      ),
    },
    {
      id: "item-5",
      question: "Do I need to run FocusPetNativeHost.exe manually?",
      category: "System",
      answer: (
        <div className="space-y-2 text-xs sm:text-sm text-slate-600 leading-relaxed">
          <p className="font-bold text-slate-900 text-base text-emerald-700 flex items-center gap-1.5">
            <CheckCircle2 className="w-4 h-4 text-emerald-600" />
            No.
          </p>
          <p>
            <code className="font-mono text-purple-700">FocusPetNativeHost.exe</code> is automatically launched by Google Chrome or Microsoft Edge via the browser&apos;s standard Native Messaging protocol whenever an active distraction feed is detected. You do not need to open or execute it manually.
          </p>
        </div>
      ),
    },
    {
      id: "item-6",
      question: "Do I need Python installed on my computer?",
      category: "System",
      answer: (
        <div className="space-y-2 text-xs sm:text-sm text-slate-600 leading-relaxed">
          <p className="font-bold text-slate-900 text-base text-emerald-700 flex items-center gap-1.5">
            <CheckCircle2 className="w-4 h-4 text-emerald-600" />
            No.
          </p>
          <p>
            The released <code className="font-mono text-purple-700">FocusPet-Setup.exe</code> installer is completely self-contained. It packages the full application runtime, graphics, and native messaging host. No external Python or dependencies are required.
          </p>
        </div>
      ),
    },
    {
      id: "item-7",
      question: "Do I need to manually edit the Windows Registry?",
      category: "System",
      answer: (
        <div className="space-y-2 text-xs sm:text-sm text-slate-600 leading-relaxed">
          <p className="font-bold text-slate-900 text-base text-emerald-700 flex items-center gap-1.5">
            <CheckCircle2 className="w-4 h-4 text-emerald-600" />
            No.
          </p>
          <p>
            The FocusPet installer automatically sets up the required Native Messaging Host registry keys under your Windows user account (<code className="font-mono text-slate-700">HKCU\Software\Google\Chrome\NativeMessagingHosts</code> and <code className="font-mono text-slate-700">HKCU\Software\Microsoft\Edge\NativeMessagingHosts</code>). Users never need to touch the Registry Editor.
          </p>
        </div>
      ),
    },
  ];

  return (
    <div id="troubleshooting" className="scroll-mt-24 rounded-3xl bg-white border border-slate-200 p-6 sm:p-8 shadow-xs">
      {/* Header */}
      <div className="max-w-3xl mb-8">
        <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-purple-50 border border-purple-200 text-xs font-semibold text-purple-700 mb-3">
          <HelpCircle className="w-3.5 h-3.5" />
          <span>Help &amp; Frequently Asked Questions</span>
        </div>
        <h2 className="text-2xl sm:text-3xl font-bold tracking-tight text-slate-900 mb-2">
          Troubleshooting &amp; FAQ
        </h2>
        <p className="text-sm text-slate-600 leading-relaxed">
          Quick solutions for unpacked extension loading, native messaging status, and runtime questions.
        </p>
      </div>

      {/* Accordion List */}
      <div className="space-y-3">
        {faqs.map((faq) => {
          const isOpen = openIds.includes(faq.id);
          return (
            <div
              key={faq.id}
              className={`rounded-2xl border transition-all duration-200 overflow-hidden ${
                isOpen
                  ? "bg-slate-50/70 border-purple-200 shadow-2xs"
                  : "bg-white border-slate-200 hover:border-slate-300"
              }`}
            >
              <button
                type="button"
                onClick={() => toggleItem(faq.id)}
                aria-expanded={isOpen}
                className="w-full p-4 sm:p-5 text-left flex items-center justify-between gap-4 font-bold text-slate-900 hover:text-purple-700 transition-colors"
              >
                <div className="flex items-center gap-2.5">
                  <span className="text-xs px-2 py-0.5 rounded-md bg-purple-100 text-purple-800 font-mono font-medium hidden sm:inline-block">
                    {faq.category}
                  </span>
                  <span className="text-sm sm:text-base">{faq.question}</span>
                </div>
                <ChevronDown
                  className={`w-4 h-4 text-slate-400 shrink-0 transition-transform duration-200 ${
                    isOpen ? "rotate-180 text-purple-600" : ""
                  }`}
                />
              </button>

              {isOpen && (
                <div className="px-4 sm:px-5 pb-5 pt-1 border-t border-slate-200/60 animate-in fade-in duration-150">
                  {faq.answer}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
